Updated Dockerfile to combine all ENV's to one line and updates to the "if" statement to actually make it work!

diff --git a/j8/Dockerfile b/j8/Dockerfile
--- a/j8/Dockerfile
+++ b/j8/Dockerfile
@@ -21,34 +21,34 @@ RUN apt-get update \
     && apt-get install -y wget unzip \
     && rm -rf /var/lib/apt/lists/*
 
-# Install JRE
-ENV JAVA_VERSION 8
-ENV JAVA_RMF 0.2.0
-ENV JAVA_VRMF $JAVA_VERSION.$JAVA_RMF
-ENV JAVA_TYPE jre
-ENV JAVA_EDITION javase
-ENV RUNTIMES_URL http://j9.ottawa.ibm.com/j9dt/incubator/virt/dhe/ibmruntimes/java/
+ENV JAVA_VERSION=8 \
+    JAVA_RMF=0.2.0 \
+    JAVA_TYPE="jre" \
+    JAVA_EDITION="javase" \
+    RUNTIMES_URL="http://j9.ottawa.ibm.com/j9dt/incubator/virt/dhe/ibmruntimes/java/"
 
+# Install JRE if the downloaded md5sum matches what is available in the .yml file
 RUN TARCH=$(uname -p) \
+    && JAVA_VRMF=$JAVA_VERSION.$JAVA_RMF \
     && YML_FILENAME=ibm-java-$JAVA_TYPE-$JAVA_VERSION.$JAVA_RMF-linux-$TARCH-$JAVA_EDITION.yml \
     && wget -q -O /tmp/$YML_FILENAME $RUNTIMES_URL/$JAVA_VERSION/$YML_FILENAME \
     && JAVA_URL=$(cat /tmp/$YML_FILENAME | sed -n '/'$JAVA_VRMF'/{n;p}' | sed -n 's/\s*uri:\s//p' | tr -d '\r') \
-    && ESUM=$(cat /tmp/$YML_FILENAME | sed -n '/'$JAVA_VRMF'/,/md5sum/p' | sed -n 's/\s*md5sum:\s//p' | tr -d '\r') \
     && wget -q $JAVA_URL -U UA-IBM-JAVA-Docker -O /tmp/ibm-java.bin \
-    && ASUM=$(md5sum /tmp/ibm-java.bin) \
+    && ESUM=$(cat /tmp/$YML_FILENAME | sed -n '/'$JAVA_VRMF'/,/md5sum/p' | sed -n 's/\s*md5sum:\s//p' | tr -d '\r') \
+    && ASUM=$(md5sum /tmp/ibm-java.bin | cut -d" " -f1) \
     && if [ "$ESUM" = "$ASUM" ]; then \
-         chmod +x /tmp/ibm-java.bin \
-         echo "INSTALLER_UI=silent" > /tmp/response.properties \
-         echo "USER_INSTALL_DIR=/opt/ibm/java" >> /tmp/response.properties \
-         echo "LICENSE_ACCEPTED=TRUE" >> /tmp/response.properties \
-         mkdir /opt/ibm \
-         /tmp/ibm-java.bin -i silent -f /tmp/response.properties \
-         rm /tmp/response.properties \
+          chmod +x /tmp/ibm-java.bin; \
+          echo "INSTALLER_UI=silent" > /tmp/response.properties; \
+          echo "USER_INSTALL_DIR=/opt/ibm/java" >> /tmp/response.properties; \
+          echo "LICENSE_ACCEPTED=TRUE" >> /tmp/response.properties; \
+          mkdir /opt/ibm; \
+          /tmp/ibm-java.bin -i silent -f /tmp/response.properties; \
+          rm -f /tmp/response.properties; \
        else \
-         echo "ERROR: md5sum of the downloaded file does not match" \
-         exit 1; \
+          echo "ERROR: md5sum of the downloaded file does not match"; \
+          exit 1; \
        fi \
-    && rm /tmp/ibm-java.bin
-ENV JAVA_HOME /opt/ibm/java
-ENV PATH $JAVA_HOME/jre/bin:$PATH
+    && rm -f /tmp/ibm-java.bin
 
+ENV JAVA_HOME=/opt/ibm/java \
+    PATH=/opt/ibm/java/jre/bin:$PATH
